import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/Redux/ReduxProvider/ReduxProvider";
import { NavigationEvents } from "@/provider/navigation-events/NavigationEvents";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Estrella | Home",
  description: "Generated by Estrella",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <NavigationEvents>
            {children}
            <ToastContainer/>
          </NavigationEvents>
        </ReduxProvider>
      </body>
    </html>
  );
}
