export const helpInfo = [
    {
        title: "Welcome",
        description: "Fabrilife is the first and largest print-on-demand online platform in Bangladesh, which might as well be the game changer in the clothing industry of the country. Fabrilife may be the only one among the existing business models that requires absolute zero investment to initiate and guarantees significant recognition and profits in virtually non-existent legwork and absolutely minimal efforts .  All you need to do is bring your creativity and help spread the word, we’ll take care of the rest. "
    },
    {
        title: "How do we work?",
        description: "Our buyers can either browse through the enormous collections of  crowdsourced designs from our gallery and choose , or fancy something absolutely unique for themselves by making their own design using our design creator. You have all the tools you need. Fabrilife also encourages people to sell their custom designed products with no registration fee, risk, hassle or legworks. Fabrilife is 100% free to use.  During the creation of your campaign , a  price is automatically being set by our system (which is calculated considering various socio-economic and technical factors)  and as a seller you will set additional pricing on top of that. After the campaign is published to our site, you will grab a solid 75% of profit when that campaigned product is sold from our site.You as a seller can add ৳30 to ‎৳200 (max) over the system calculated price . Now when the product will be sold, you will be earning  a fixed 75% of that additional amount ‎for each unit which can be ‎maximum of ৳150 .Remember, all the designs available in Fabrilife are completely outsourced by the general population around the world, and they do it for free. This is a massive gathering of creative people who fancy art and fashion, and we tribute their talents and efforts by sharing profits. Whether you are a buyer or a seller, whenever you enter Fabrilife, you enter the art gallery version of a Fashion website. Just explore and enjoy how creative human being can truly be with their ideas, visions and passions for art."
    },
    {
        title: "Why Fabrilife Products are different than you think?",
        description: "Tee’s are the most basic and lovable form of wearable products in Bangladesh. From Young to Old, Boys or Girls, even little Kids, we all feel more comfortable wearing Tee’s probably more than any other form of clothings. And certainly you will find various Tee brand and non-brand houses producing number of different variations of Tee’s countrywide within variable price range. One thing that Fabrilife offers you (which nobody else did before in such a grandiose manner in Bangladesh) is to make your own custom Tee. Until now, you will almost certainly won’t be able to buy a Tee from somewhere which is not being worn by somebody else. But in here, you have the opportunity to become truly unique when it comes to fashion. For example, You have a good theme or few words wandering around inside your head ?  you can convert that into a digital image and print that into your Tee via our website. Or, you want to tell something lovely/not-so-lovely/poetic/sarcastic to someone you cannot speak to in person? you let us know the message and we print that on a Tee and send to that person. All you need is to let us know your thoughts and relax, we will do the rest. But let's say, you are not that much into “converting” thoughts into shapes or words.  Doesn’t matter. We are presenting you something unthinkable. We are introducing you to a gallery full of dreams, dreams of the mass population. Our gallery is full of Tee’s where thousands of ideas are integrated from artists who might live next door to you, close to you, a friend of you who is always shy and quiet and you didn’t know anything about his art skills until now, when you found a Fabrilife store of his own full of startling designs. Your dreams and thoughts are always yours. Whether you decide to keep it for you only or to share it with others it is completely up to you, but for either purpose, you will certainly not find a better place than Fabrilife."
    },

    {
        title: "Our Pricing",
        description: "We have introduced 'Pay-As-You-Draw', and Artificial Intelligence featured system where you will find a thoroughly calculated pricing system for base prices that consider various factors during a Tee production in our unique printing  technology. The base pricing you find for our Tee’s is calculated with a combination of the  printing cost + garment cost + production cost + Fabrilife profit margin. Additionally , when someone wants to sell the product, they set additional values. So every product you buy from our website’s gallery, be assured that a portion of that money is going to the person who is the creator of that design that you will be wearing cheerfully on your Tee"
    },
]

